language: ruby

rvm:
  - 2.2.0

before_script:
  - bundle exec rake compile
  - bundle exec ruby bin/ruby-spark build

cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
